package org.fit.cssbox.scriptbox.security;

public enum SandboxingFlag {
	NAVIGATION_BROWSING_CONTEXT_FLAG,
	AUXILARY_NAVIGATION_BROWSING_CONTEXT_FLAG,
	TOPLEVEL_NAVIGATION_BROWSING_CONTEXT_FLAG,
	PLUGINS_BROWSING_CONTEXT_FLAG,
	SEAMLESS_IFRAMES_FLAG,
	ORIGIN_BROWSING_CONTEXT_FLAG,
	FORMS_BROWSING_CONTEXT_FLAG,
	POINTER_LOCK_BROWSING_CONTEXT_FLAG,
	SCRIPTS_BROWSING_CONTEXT_FLAG,
	AUTOMATIC_FEATURES_BROWSING_CONTEXT_FLAG,
	FULLSCREEN_BROWSING_CONTEXT_FLAG,
	DOCUMENT_DOMAIN_BROWSING_CONTEXT_FLAG
}
